### ISSUE TITLE
Property 'request' of exported class expression may not be private or protected.ts(4094)

### ISSUE THREAD

**Issue by svnty** [sstur/nbit#15]
![Screen Shot 2023-12-13 at 7 17 06 pm](https://github.com/sstur/nbit/assets/47465827/2928f181-05f1-4add-a51e-6d4efb3fe3d7)

What am I doing wrong?

![Screen Shot 2023-12-13 at 7 17 50 pm](https://github.com/sstur/nbit/assets/47465827/a2724876-8d66-4cb6-b701-8e8f595c284f)

**Comment by sstur** [comment]
This is strange, I've not seen this one before. And your code looks fine. What version of TS are you on? Ensure you're using the same version in VS Code and in the codebase. At the terminal you can run `cat node_modules/typescript/package.json | grep version` and in VS code click on the curly braces near the word "TypeScript" in the status bar.

<img width="165" alt="image" src="https://github.com/sstur/nbit/assets/369384/15942c38-7d8a-4a87-9884-eeb0fdc2a394">

If you have a minimal reproducible example that I can run on my side, that would help.

**Comment by sstur** [comment]
Oh, also could you paste the contents of your tsconfig file?

According to [this issue](https://github.com/microsoft/TypeScript/issues/30355), it might be related to having "declaration emit enabled" in your config.

> anonymous classes can't have private or protected members if declaration emit is enabled

**Comment by svnty** [comment]
`    "version": "5.3.3",`

My source code is available here
https://github.com/medicamina/api/tree/main

```json
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "react-jsx",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "types": [
      "bun-types" // add Bun global
    ]
  }
}

```

**Comment by svnty** [comment]
What's strange is that the code compiles and runs without errors or warnings, it's just VS code complaining about types

**Comment by svnty** [comment]
I fixed it

**The troublemaker**
![Screen Shot 2024-01-02 at 9 00 13 pm](https://github.com/sstur/nbit/assets/47465827/23734896-6e57-4120-8882-3c9c94ab52d1)

**The new problem**
![Screen Shot 2024-01-02 at 9 05 37 pm](https://github.com/sstur/nbit/assets/47465827/8ffd6ad2-56b2-4ac5-ac29-9559a58aca80)

**VS Code's fix**
![Screen Shot 2024-01-02 at 9 05 43 pm](https://github.com/sstur/nbit/assets/47465827/b669e113-b7f0-4df0-9bb9-85353938524c)

Source code [https://github.com/svnty/nbit/blob/main/packages/core/src/core/CustomRequest.ts](https://github.com/svnty/nbit/blob/main/packages/core/src/core/CustomRequest.ts)
