### ISSUE TITLE
`request.json` cannot be deconstructed

### ISSUE THREAD

**Issue by ImLunaHey** [sstur/nbit#2]
The following doesn't work. I'm forced to use `await request.json()`.

```ts
app.put('/org/:id', async ({ json }) => {
    const body = await json();
}),
```

```ts
Application started 
114 |   }
115 |   text() {
116 |     return this.request.text();
117 |   }
118 |   async json() {
119 |     const contentType = getContentType(this.headers);
                                          ^
TypeError: undefined is not an object (evaluating 'this.headers')
      at /Users/xo/code/ImLunaHey/paas/node_modules/@nbit/bun/index.js:119:39
      at json (/Users/xo/code/ImLunaHey/paas/node_modules/@nbit/bun/index.js:118:15)
      at /Users/xo/code/ImLunaHey/paas/src/service-registry.ts:163:35
      at /Users/xo/code/ImLunaHey/paas/src/service-registry.ts:161:37
      at /Users/xo/code/ImLunaHey/paas/node_modules/@nbit/bun/index.js:161:31
```

**Comment by ImLunaHey** [comment]
You likely need to use a lib like https://www.npmjs.com/package/auto-bind or bind the methods manually to the class.

**Comment by sstur** [comment]
I tried this in the browser, to see how standards-compliant [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) class handles this, and it appears to also error (see below).

I can see the case for wanting to destructure inline like you're doing there, but I'm hesitant to do it unless I can be sure of the performance implications. I'd need to run an experiment and measure perf, but I don't know when I could get to this. For now closing as standards compliant behavior.

<img width="1083" alt="image" src="https://github.com/sstur/nbit/assets/369384/8dec59a2-bddc-4ef0-bae6-e1fe662dec43">
