### ISSUE TITLE
Support for custom request methods?

### ISSUE THREAD

**Issue by ImLunaHey** [sstur/nbit#9]
I noticed there's no way to define a custom request method.

Is this something that could possibly be added?

**Comment by sstur** [comment]
What would be an example of a custom request method, you mean like instead of `GET|PUT|POST|DELETE` you'd want something like `FOO`?

Do other frameworks support this? What would be a use case for such a thing?

**Comment by ImLunaHey** [comment]
Most others do in one way or another.

WebDAV servers for example uses non-standard methods like `MKCOL` and `PROPFIND`. I've run into a few times in the past where I've needed this.

A solution for now would be to use `*` and then do my own checks on `request.method`.

**Comment by sstur** [comment]
Oh, interesting. I haven't thought about WebDAV in a very long time, but you're right, that's a legit use case for strange request methods.

I think you're right, the workaround for now is to use the `*`, but I'll see about adding support for any arbitrary string like so:
```
  app.route('MKCOL', '/webdav', (request) => {
    return new Response(...);
  }),
```

**Comment by sstur** [comment]
Done. This is now possible in [v0.10](https://github.com/sstur/nbit/releases/tag/v0.10.0).
